import XCTest
@testable import BeautifulMermaid

final class GitGraphModelTests: XCTestCase {

    private func lines(_ source: String) -> [String] {
        source.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
    }

    private func parse(_ source: String) throws -> GitGraphDiagram {
        var config = GitGraphConfig()
        config.mainBranchName = "main"
        return try parseGitGraph(lines(source), frontmatter: nil)
    }

    // MARK: - Commit model tests

    func testCommitAutoGeneratedId() throws {
        let diagram = try parse("gitGraph\n   commit")
        let commit = diagram.commits[0]
        XCTAssertTrue(commit.id.contains("-"), "Auto-generated ID should contain dash: \(commit.id)")
        XCTAssertEqual(commit.seq, 0)
        XCTAssertEqual(commit.type, .normal)
        XCTAssertEqual(commit.parents, [])
        XCTAssertEqual(commit.branch, "main")
        XCTAssertFalse(commit.customId)
    }

    func testCommitOnCurrentBranch() throws {
        let diagram = try parse("gitGraph\n   commit\n   branch dev\n   commit\n   checkout main\n   commit")
        let commits = diagram.commits
        XCTAssertEqual(commits[0].branch, "main")
        XCTAssertEqual(commits[1].branch, "dev")
        XCTAssertEqual(commits[2].branch, "main")
    }

    func testCommitSequenceNumbers() throws {
        let diagram = try parse("gitGraph\n   commit\n   commit\n   commit")
        XCTAssertEqual(diagram.commits[0].seq, 0)
        XCTAssertEqual(diagram.commits[1].seq, 1)
        XCTAssertEqual(diagram.commits[2].seq, 2)
    }

    func testCommitParents() throws {
        let diagram = try parse("gitGraph\n   commit\n   commit")
        XCTAssertEqual(diagram.commits[0].parents, [])
        XCTAssertEqual(diagram.commits[1].parents, [diagram.commits[0].id])
    }

    func testCustomCommitId() throws {
        let diagram = try parse("gitGraph\n   commit id:\"custom123\"")
        let commit = diagram.commits[0]
        XCTAssertEqual(commit.id, "custom123")
    }

    // MARK: - Branch model tests

    func testBranchAutoCheckout() throws {
        let diagram = try parse("gitGraph\n   commit\n   branch develop\n   commit")
        XCTAssertEqual(diagram.branches.count, 2)
        XCTAssertTrue(diagram.branches.contains("main"))
        XCTAssertTrue(diagram.branches.contains("develop"))
        XCTAssertEqual(diagram.currentBranch, "develop")
    }

    func testCheckoutExisting() throws {
        let diagram = try parse("gitGraph\n   branch dev\n   commit\n   checkout main\n   commit")
        XCTAssertEqual(diagram.currentBranch, "main")
    }

    func testDuplicateBranchError() throws {
        XCTAssertThrowsError(try parse("gitGraph\n   commit\n   branch dev\n   branch dev")) { error in
            guard let dbError = error as? GitGraphDBError else {
                XCTFail("Expected GitGraphDBError"); return
            }
            switch dbError {
            case .duplicateBranch:
                break
            default:
                XCTFail("Expected duplicateBranch error, got \(dbError)")
            }
        }
    }

    func testCheckoutUnknownError() throws {
        XCTAssertThrowsError(try parse("gitGraph\n   checkout dev")) { error in
            guard let dbError = error as? GitGraphDBError else {
                XCTFail("Expected GitGraphDBError"); return
            }
            switch dbError {
            case .checkoutUnknownBranch:
                break
            default:
                XCTFail("Expected checkoutUnknownBranch error, got \(dbError)")
            }
        }
    }

    // MARK: - Merge model tests

    func testMergeFromBranch() throws {
        let diagram = try parse("gitGraph\n   commit\n   branch dev\n   commit\n   checkout main\n   merge dev")
        let mergeCommit = diagram.commits.last!
        XCTAssertEqual(mergeCommit.type, .merge)
        XCTAssertEqual(mergeCommit.parents.count, 2)
    }

    func testMergeMessage() throws {
        let diagram = try parse("gitGraph\n   commit\n   branch dev\n   commit\n   checkout main\n   merge dev")
        let mergeCommit = diagram.commits.last!
        XCTAssertTrue(mergeCommit.message.contains("merged branch dev into main"))
    }

    func testMergeUnknownBranch() throws {
        XCTAssertThrowsError(try parse("gitGraph\n   commit\n   merge dev")) { error in
            guard let dbError = error as? GitGraphDBError else { return }
            switch dbError {
            case .mergeUnknownBranch: break
            default: XCTFail("Expected mergeUnknownBranch")
            }
        }
    }

    func testMergeEmptyCurrent() throws {
        XCTAssertThrowsError(try parse("gitGraph\n   branch dev\n   commit\n   checkout main\n   merge dev")) { error in
            guard let dbError = error as? GitGraphDBError else { return }
            switch dbError {
            case .mergeEmptyCurrent: break
            default: XCTFail("Expected mergeEmptyCurrent, got \(dbError)")
            }
        }
    }

    func testMergeEmptyTarget() throws {
        XCTAssertThrowsError(try parse("gitGraph\n   commit\n   branch dev\n   checkout main\n   merge dev")) { error in
            guard let dbError = error as? GitGraphDBError else { return }
            switch dbError {
            case .mergeSameHead: break
            default: XCTFail("Expected mergeSameHead, got \(dbError)")
            }
        }
    }

    func testMergeSameHead() throws {
        XCTAssertThrowsError(try parse("gitGraph\n   commit\n   branch dev\n   checkout dev\n   merge dev")) { error in
            guard let dbError = error as? GitGraphDBError else { return }
            switch dbError {
            case .mergeIntoSelf: break
            default: XCTFail("Expected mergeIntoSelf, got \(dbError)")
            }
        }
    }

    func testMergeCustomId() throws {
        let diagram = try parse("gitGraph\n   commit\n   commit\n   branch dev\n   commit\n   checkout main\n   merge dev id:\"customMerge\"")
        let mergeCommit = diagram.commits.last!
        XCTAssertEqual(mergeCommit.id, "customMerge")
        XCTAssertTrue(mergeCommit.customId)
    }

    // MARK: - Cherry-pick model tests

    func testCherryPickBasic() throws {
        let diagram = try parse("gitGraph\n   commit id:\"A\"\n   branch dev\n   commit id:\"B\"\n   checkout main\n   cherry-pick id:\"B\"")
        let cpCommit = diagram.commits.last!
        XCTAssertEqual(cpCommit.type, .cherryPick)
        XCTAssertEqual(cpCommit.parents.count, 2)
        XCTAssertTrue(cpCommit.tags.first?.contains("cherry-pick:B") ?? false)
    }

    func testCherryPickMissingSource() throws {
        XCTAssertThrowsError(try parse("gitGraph\n   commit\n   cherry-pick")) { error in
            guard let dbError = error as? GitGraphDBError else { return }
            switch dbError {
            case .cherryPickMissingSource: break
            default: XCTFail("Expected cherryPickMissingSource")
            }
        }
    }

    func testCherryPickSameBranch() throws {
        XCTAssertThrowsError(try parse("gitGraph\n   commit id:\"A\"\n   cherry-pick id:\"A\"")) { error in
            guard let dbError = error as? GitGraphDBError else { return }
            switch dbError {
            case .cherryPickSameBranch: break
            default: XCTFail("Expected cherryPickSameBranch, got \(dbError)")
            }
        }
    }

    func testCherryPickEmptyCurrent() throws {
        XCTAssertThrowsError(try parse("gitGraph\n   branch dev\n   commit id:\"A\"\n   checkout main\n   cherry-pick id:\"A\"")) { error in
            guard let dbError = error as? GitGraphDBError else { return }
            switch dbError {
            case .cherryPickEmptyCurrent: break
            default: XCTFail("Expected cherryPickEmptyCurrent, got \(dbError)")
            }
        }
    }

    // MARK: - Config tests

    func testMainBranchNameConfig() throws {
        var config = GitGraphConfig()
        config.mainBranchName = "trunk"
        let diagram = try parseGitGraph(lines("gitGraph\n   commit"), frontmatter: DiagramFrontmatter(gitGraphConfig: config))
        XCTAssertEqual(diagram.currentBranch, "trunk")
        let commit = diagram.commits[0]
        XCTAssertEqual(commit.branch, "trunk")
    }

    func testBranchOrdering() throws {
        let diagram = try parse("gitGraph\n   commit\n   branch test1 order:1\n   branch test2\n   branch test3")
        let branches = diagram.branches
        XCTAssertEqual(branches.count, 4)
        XCTAssertTrue(branches.contains("main"))
        XCTAssertTrue(branches.contains("test1"))
        XCTAssertTrue(branches.contains("test2"))
        XCTAssertTrue(branches.contains("test3"))
    }
}
