// Semantic icon map (formerly generated). Hand-maintained.

public enum DSIcon: String, CaseIterable, Sendable {
    case close, search, settings, reset, run, export, convert, diagnostics, warning, error, info, success, disclosureDown, disclosureRight, add, remove, copy, history, theme, code, node, diagram, subgraph, favorite, image, rearrange, cursor, pan, marquee, connector, undo, redo, panZoom, grid, expand, alignLeading, alignCenterHorizontal, alignTrailing, alignTop, alignCenterVertical, alignBottom, organize, browse, general, renderBackend, platformParity, mutations, fonts

    public var systemName: String {
        switch self {
        case .close: "xmark"
        case .search: "magnifyingglass"
        case .settings: "slider.horizontal.3"
        case .reset: "arrow.counterclockwise"
        case .run: "play.fill"
        case .export: "square.and.arrow.up"
        case .convert: "arrow.left.arrow.right"
        case .diagnostics: "exclamationmark.bubble"
        case .warning: "exclamationmark.triangle.fill"
        case .error: "xmark.octagon.fill"
        case .info: "info.circle.fill"
        case .success: "checkmark.circle.fill"
        case .disclosureDown: "chevron.down"
        case .disclosureRight: "chevron.right"
        case .add: "plus"
        case .remove: "minus"
        case .copy: "doc.on.doc"
        case .history: "clock.arrow.circlepath"
        case .theme: "paintpalette"
        case .code: "chevron.left.slash.chevron.right"
        case .node: "rectangle"
        case .diagram: "square.on.square"
        case .subgraph: "square.on.square"
        case .favorite: "star"
        case .image: "photo"
        case .rearrange: "arrow.triangle.2.circlepath"
        case .cursor: "cursorarrow"
        case .pan: "hand.raised"
        case .marquee: "rectangle.dashed"
        case .connector: "arrow.left.and.right"
        case .undo: "arrow.uturn.backward"
        case .redo: "arrow.uturn.forward"
        case .panZoom: "arrow.up.and.down.and.arrow.left.and.right"
        case .grid: "grid"
        case .expand: "arrow.up.left.and.arrow.down.right"
        case .alignLeading: "align.horizontal.left.fill"
        case .alignCenterHorizontal: "align.horizontal.center.fill"
        case .alignTrailing: "align.horizontal.right.fill"
        case .alignTop: "align.vertical.top.fill"
        case .alignCenterVertical: "align.vertical.center.fill"
        case .alignBottom: "align.vertical.bottom.fill"
        case .organize: "list.bullet.indent"
        case .browse: "folder"
        case .general: "gearshape"
        case .renderBackend: "rectangle.on.rectangle"
        case .platformParity: "rectangle.split.2x1"
        case .mutations: "number"
        case .fonts: "textformat"
        }
    }
}
