# diagramkit:family=sequence
shape: sequence_diagram

alice: "Alice"
bob: "Bob"
alice -> bob: "Hello"
# diagramkit:seq-arrow-type=0,0
bob -> alice: "Hi"
# diagramkit:seq-arrow-type=1,0
alice -> alice: "thinking"
# diagramkit:seq-arrow-type=2,0
